import { Column, ColumnId, Task, User, UserRole } from '../../shared/models/task.model';

export const COLUMN_META: { id: ColumnId; title: string; color: string }[] = [
  { id: 'backlog', title: 'Backlog', color: '#9b9890' },
  { id: 'todo', title: 'To Do', color: '#2d6fa3' },
  { id: 'inprogress', title: 'In Progress', color: '#e8a033' },
  { id: 'review', title: 'In Review', color: '#8b6ec0' },
  { id: 'done', title: 'Done', color: '#3a7d5a' },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'mg',
    name: 'Maya G.',
    initials: 'MG',
    role: UserRole.MANAGER,
    avatarColor: '#c17b3a',
    avatarBg: '#f5ead8',
  },
  {
    id: 'tk',
    name: 'Tom K.',
    initials: 'TK',
    role: UserRole.TEAM_LEAD,
    avatarColor: '#2d6fa3',
    avatarBg: '#e8f1f8',
  },
  {
    id: 'sa',
    name: 'Sara A.',
    initials: 'SA',
    role: UserRole.EMPLOYEE,
    avatarColor: '#6b4ea0',
    avatarBg: '#f0ebf8',
  },
  {
    id: 'rj',
    name: 'Raj J.',
    initials: 'RJ',
    role: UserRole.EMPLOYEE,
    avatarColor: '#3a7d5a',
    avatarBg: '#e6f3ec',
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    _id: 't1',
    columnId: 'todo',
    title: 'Redesign navigation menu',
    description: 'Update the top nav with new brand colors and improved mobile responsiveness.',
    priority: 'high',
    tags: ['Design', 'Frontend'],
    assignedTo: 'sa',
    createdById: 'mg',
    files: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    order: 1,
  },
  {
    _id: 't2',
    columnId: 'inprogress',
    title: 'Set up CI/CD pipeline',
    description: 'Configure GitHub Actions for automated testing and deployment to staging.',
    priority: 'medium',
    tags: ['DevOps', 'Backend'],
    assignedTo: 'tk',
    createdById: 'tk',
    files: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    order: 2,
  },
  {
    _id: 't3',
    columnId: 'todo',
    title: 'Fix login page bug',
    description: 'Users report intermittent 401 errors on mobile devices running iOS 16.',
    priority: 'high',
    tags: ['Bug', 'Frontend'],
    assignedTo: 'rj',
    createdById: 'mg',
    files: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    order: 3,
  },
  {
    _id: 't4',
    columnId: 'inprogress',
    title: 'Write API documentation',
    description: 'Document all REST endpoints with request/response examples.',
    priority: 'low',
    tags: ['Backend'],
    assignedTo: 'mg',
    createdById: 'mg',
    files: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    order: 4,
  },
  {
    _id: 't5',
    columnId: 'review',
    title: 'Dark mode implementation',
    description: 'Add system-level dark mode support across all pages.',
    priority: 'medium',
    tags: ['Frontend', 'Design'],
    assignedTo: 'sa',
    createdById: 'tk',
    files: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    order: 5,
  },
  {
    _id: 't6',
    columnId: 'done',
    title: 'Database schema migration',
    description: 'Migrate users table to support OAuth social logins.',
    priority: 'medium',
    tags: ['Backend'],
    assignedTo: 'tk',
    createdById: 'mg',
    files: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    order: 6,
  },
  {
    _id: 't7',
    columnId: 'backlog',
    title: 'User onboarding flow',
    description: 'Design and build a 3-step onboarding wizard for new signups.',
    priority: 'low',
    tags: ['Design', 'Feature'],
    assignedTo: 'sa',
    createdById: 'mg',
    files: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    order: 7,
  },
];
